import { atom, atomFamily } from "recoil";
import * as Displays from "../../Nodes/Displays";
import * as Pipes from "../../Nodes/Pipes";
import * as Inputs from "../../Nodes/Inputs";
import { Edge, Node } from "reactflow";

// TODO: Add a helper function to automate this.
export const nodeTypesState = atom({
  key: "nodeTypes",
  default: {
    //  -------
    // | Inputs |
    //  -------
    numberInputNode: Inputs.NumberInputNode,
    stringInputNode: Inputs.StringInputNode,
    buttonInputNode: Inputs.ButtonInputNode,
    anyInputNode: Inputs.AnyInputNode,

    //  -------
    // | PIPES |
    //  -------

    // MATH
    multiplicationNode: Pipes.MuliplicationNode,
    divisionNode: Pipes.DivisionNode,
    moduloNode: Pipes.ModuloNode,
    minNode: Pipes.MinNode,
    maxNode: Pipes.MaxNode,
    additionNode: Pipes.AdditionNode,
    subtractionNode: Pipes.SubtractionNode,
    stringConcatNode: Pipes.StringConcatNode,

    // CRYPTO
    hashNode: Pipes.HashNode,
    sharedSecretNode: Pipes.SharedSecretNode,
    keyPairNode: Pipes.KeyPairNode,
    encryptNode: Pipes.EncryptNode,

    // LOGIC
    andNode: Pipes.ANDNode,
    notNode: Pipes.NOTNode,
    orNode: Pipes.ORNode,
    xorNode: Pipes.XORNode,

    // ETHERS
    providerNode: Pipes.ProviderNode,
    getBalanceNode: Pipes.GetBalanceNode,
    contractNode: Pipes.ContractNode,

    //  ---------
    // | Displays |
    //  ---------
    numberDisplayNode: Displays.NumberDisplayNode,
    stringDisplayNode: Displays.StringDisplayNode,
    multiDisplayNode: Displays.MultiDisplayNode,
    arrayDisplayNode: Displays.ArrayDisplayNode,
    addressDisplayNode: Displays.AddressDisplayNode,
    conditionalDisplayNode: Displays.ConditionalDisplayNode,
    booleanDisplayNode: Displays.BooleanDisplayNode,

    valueNode: Pipes.ValueNode,
  },
});

export const nodeTypesPrettyState = atom({
  key: "nodeTypesPretty",
  default: {
    Input: {
      numberInputNode: "Number",
      stringInputNode: "String",
      buttonInputNode: "Button",
      anyInputNode: "Any",
    },
    Display: {
      numberDisplayNode: "Number",
      stringDisplayNode: "String",
      multiDisplayNode: "Multi",
      arrayDisplayNode: "Array",
      addressDisplayNode: "Address",
      conditionalDisplayNode: "Conditional",
      booleanDisplayNode: "Boolean",
    },
    // TODO: Add storage maybe?
    // Storage: {},
    // TODO: Add axios api interfaces
    Network: {},
    Crypto: {
      hashNode: "Hash",
      sharedSecretNode: "Shared Secret",
      keyPairNode: "Key Pair",
      encryptNode: "Encrypt",
    },
    Ethers: {
      providerNode: "Provider",
      getBalanceNode: "Balance",
      contractNode: "Contract",
    },
    Control: {
      andNode: "AND",
      notNode: "NOT",
      orNode: "OR",
      xorNode: "XOR",
    },
    Math: {
      multiplicationNode: "Multiplication",
      additionNode: "Addition",
      subtractionNode: "Subtraction",
      divisionNode: "Division",
      moduloNode: "Modulo",
      minNode: "Min",
      maxNode: "Max",
    },
    // TODO: Fill with ethers utils
    Utils: {},
    String: {
      stringConcatNode: "Concat",
      valueNode: "ValueNode",
    },
    // TODO ADD THIS
    Object: {},
  },
});

export const nodeState = atom<Array<Node>>({
  key: "nodes",
  default: [],
});

export const edgeState = atom<Array<Edge>>({
  key: "edges",
  default: [],
});

//@params: nodeID: string
export const nodeDataState = atomFamily<any, string>({
  key: "nodeDataState",
  dangerouslyAllowMutability: true,
  default: (nodeID) => {
    return {
      a: undefined,
      b: undefined,
      c: undefined,
      d: undefined,
      e: undefined,
      f: undefined,
      g: undefined,
      h: undefined,
      i: undefined,
      j: undefined,
      k: undefined,
      l: undefined,
      m: undefined,
      n: undefined,
      o: undefined,
      p: undefined,
      inputTypes: undefined,
      outputTypes: undefined,
      name: undefined,
      id: nodeID,
    };
  },
});

export const cursorPositionState = atom({
  key: "cursorPositionState",
  default: { x: 0, y: 0 },
});

export const blockNumberState = atom({
  key: "blockNumberState",
  default: 0,
  dangerouslyAllowMutability: true,
});

export const chainIdState = atom({
  key: "chainIdState",
  default: 1,
});

// @notice This is a global variable that is used to keep track of various things we use often. Like providers or latest block number etc.
export const globalVariablesState = atom({
  key: "globalVariablesState",
  default: {
    // provider: new ethers.providers.AlchemyProvider(process.env.REACT_APP_ALCHEMY_ENDPOINT),
  },
});

export const nodeNameState = atom({
  key: "nodeNameState",
  default: [
    "⚡️TurboETH - Web3 Build System",
    "🐍 snekmate",
    "0xPARC",
    "0xSplits",
    "Across Protocol",
    "Agora",
    "Akula",
    "Ankr",
    "Ante",
    "Apetimism Launchpad",
    "Atlantis World",
    "Attestation Station Interface",
    "Bankless Academy",
    "BanklessDAO Projects",
    "Basic course in crypto literacy",
    "beaconcha.in",
    "Big Sybil'or",
    "Blobscan",
    "Blockscout",
    "Blocktrend (區塊勢)",
    "blst by Supranational",
    "Boardroom",
    "Bored Town",
    "BuidlGuidl",
    "BwareLabs",
    "CANDIDE Wallet",
    "Cannon",
    "Chaineye",
    "Chainlist",
    "ChugSplash",
    "Clique",
    "Commons Stack",
    "cp0x",
    "Crate-Crypto",
    "Cryptocurrency and Friends",
    "CryptoStats",
    "Cryptoversidad",
    "CryptoZombies",
    "Dapp-Learning",
    "DeFi Library",
    "DefiLlama",
    "delegation.tools",
    "DexKit",
    "diligit",
    "dm3 protocol",
    "donnoh",
    "Duniversity (Dune Education)",
    "EIP-5164 / PoolTogether Inc",
    "EIP4844 collection",
    "Eneagon by zenbit.eth",
    "ERC-5560: Redeemable NFTs",
    "Erigon",
    "Espacio Cripto",
    "Esteroids",
    "eth.limo",
    "EthereansOS",
    "ETHEREUM MÉXICO",
    "EthereumETL",
    "EthernautDAO",
    "Ethers",
    "ETHGlobal",
    "Filosofía Código",
    "Fire",
    "Flexible Voting",
    "Flipside Crypto",
    "Forta",
    "Foundry",
    "Fractal Visions",
    "Frame",
    "GasHawk",
    "Gelato",
    "geth",
    "Gitcoin",
    "GiveStation",
    "Giveth",
    "Goerli",
    "Gov",
    "Guild",
    "H.E.R. DAO LATAM",
    "hardhat-deploy",
    "hildobby's Dune dashboards",
    "Hop Protocol",
    "Hyperledger Besu",
    "IC3",
    "Infinitism (ERC-4337)",
    "Infinity Wallet & Web3 Browser",
    "Ipsilon",
    "ITU Blockchain",
    "JiffyScan",
    "jordanmmck",
    "Jrocki - YouTube & Podcast",
    "Keccak hashing",
    "Kernel",
    "L2BEAT",
    "L2planet",
    "Launchifi",
    "Layer 2 Landscape",
    "Layer 2 Weekly Roundup",
    "Layer2DAO",
    "Lighthouse",
    "LlamaFolio",
    "Lodestar",
    "MarcoV (Optimism Dashboards)",
    "MerkleTreeJS",
    "Messari Protocol Services",
    "MetricsDAO",
    "Michael Vander Meiden",
    "Monorepo dependencies collection",
    "Multicall3",
    "MUX Protocol",
    "Nested",
    "Nethermind",
    "NFTEarth",
    "NiceNode",
    "Nimbus",
    "Node Guardians",
    "OAYC",
    "Odos",
    "OP Dashboards  by Springzhang",
    "OP Medicine",
    "OPCraft & MUD (Lattice)",
    "OpenZeppelin",
    "OptiChads",
    "Optimism Ambassador collection",
    "Optimism Cult Merch",
    "Optimism DAppNode Package",
    "Optimism en Español",
    "Optimism FM",
    "Optimism Prices Contracts",
    "OptimismArabia",
    "OptimismGuru",
    "Optinames | ENS on Optimism",
    "Orbiter Finance",
    "Ospace Project",
    "Otterscan",
    "Otterspace",
    "Pairwise",
    "Perpetuals Dune Abstraction",
    "Pocket Network",
    "Polynya",
    "Praise",
    "Prettier Solidity",
    "Proof of Integrity",
    "Protocol Guild",
    "Quark ID",
    "Questbook",
    "RadicalXChange",
    "RainbowKit Login for WordPress",
    "raise_exception (rotate.eth)",
    "RareSkills",
    "Remix Project",
    "Revoke.cash",
    "Revolte",
    "Rigoblock",
    "RockX",
    "Rollup Economics Dashboard",
    "rotki",
    "Rust-cannon-template",
    "Safe (previously Gnosis Safe)",
    "Scry",
    "SEED LATAM (formerly DeFi LATAM)",
    "Slither",
    "Small Brain Games",
    "Smock",
    "Snapshot",
    "Solady",
    "Solhint",
    "Solidity",
    "Sourcify",
    "Sugar",
    "Support NERDs collection",
    "Synpress",
    "TE Academy",
    "Teku",
    "The Optimistic Series",
    "thesleeper.eth Thai OP contents",
    "Thumbs Up Finance",
    "timdaub’s work as ETH Magician ",
    "Token Terminal",
    "Translators collection",
    "TrueBlocks",
    "TypeChain",
    "Umbra",
    "Vyper",
    "wagmi",
    "WakeUp Labs",
    "Web3 Data Degens",
    "Web3beach",
    "Web3j",
    "Week in Ethereum News",
    "Where has the OP Gone?",
    "Women Biz - Optimism education",
    "WTF Academy",
    "ZachXBT",
    "Zapper",
  ],
});
